apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutorial-server
  labels:
    app: tutorial-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutorial-server
  template:
    metadata:
      labels:
        app: tutorial-server
    spec:
      containers:
        - name: tutorial-server
          image: ghcr.io/misw-4301-desarrollo-apps-en-la-nube/argocd-tutorial:1.0
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          ports:
            - containerPort: 8080
          imagePullPolicy: Always